name: Assignment DevOps 
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 154.38.169.101
          username: leeming
          key: ${{secrets.SSH_KEY}}
          port: 8899
          script: |
            . ~/.nvm/nvm.sh
            whoami
            pwd
            ls
            git pull
            git submodule init
            git submodule update
            cd Assignment-DevOps
            pm2 restart lmServer