name: Assignment DevOps 
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 167.86.93.59
          username: leeming
          key: ${{ secrets.SSH_KEY }}
          port: 8899
          script: |
            . ~/.nvm/nvm.sh
            cd Assignment-DevOps
            git pull
            git submodule init
            git submodule update
            whoami
            pwd
            ls
            nvm install 16
            nvm use 16
            # pm2 restart devops-server
            docker compose down
            docker-compose build
            docker-compose up -d